### ISSUE TITLE
MinesweeperBoard.numberOfMinedNeighbours has no comments.

### ISSUE THREAD

**Issue by GonzalezDiana** [nmaguirre/minesweeper#53]
MinesweeperBoard.numberOfMinedNeighbours has no comments describing its expected functionality. Appropriate comments should be added to this method using javadoc.

**Comment by DanielSanchez94** [comment]
resolved in commit 9ef871d0b10f418739d624c9e07a15473d3b5af3

**Comment by letcharren** [comment]
coments are wrong. no description of the method and parameters and their descriptions are wrong

**Comment by juanpabloRV** [comment]
MinesweeperBoard.numberOfMinedNeighbours has no implementation?

**Comment by nricci** [comment]
@juanpabloRV: I just did a pull. It does have an implementation. I'm closing the issue since the comments are ok. @DanielSanchez94: I don't know if you modified the comments since the ones in the current version are different from the ones you commited. In any case if it was you that modified the comments, make  sure to always supply the most recently committed version
